apiVersion: v1
kind: Service
metadata:
  name: akash
  namespace: ck8s
spec:
  selector:
    app: akash
  ports:
    - name: p2p
      port: 26656
    - name: rpc
      port: 26657
    - name: rest
      port: 1317
    - name: grpc
      port: 9190
