apiVersion: apps/v1
kind: Deployment
metadata:
  name: ck8s-query
  namespace: ck8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ck8s-query
  template:
    metadata:
      labels:
        app: ck8s-query
    spec:
      containers:
        - name: query
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ck8s-query
            - serve
            - --grpc
            - akash.ck8s.svc.cluster.local:9190
            - --port
            - "{{ .Values.query.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.query.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.query.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
          resources: {{ toYaml .Values.query.resources | nindent 12 }}
